// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client/client.proto

/*
Package ProtobufClient is a generated protocol buffer package.

It is generated from these files:
	client/client.proto

It has these top-level messages:
	ClientMessage
	ClientIdentificationMessage
	WebAuthenticationMessage
	APIAuthenticationMessage
	ClientSubscribeMessage
	ClientUnsubscribeMessage
*/
package ProtobufClient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type APIAuthenticationMessage_Source int32

const (
	APIAuthenticationMessage_UNKNOWN        APIAuthenticationMessage_Source = 0
	APIAuthenticationMessage_GOLANG_SDK     APIAuthenticationMessage_Source = 1
	APIAuthenticationMessage_JAVASCRIPT_SDK APIAuthenticationMessage_Source = 2
)

var APIAuthenticationMessage_Source_name = map[int32]string{
	0: "UNKNOWN",
	1: "GOLANG_SDK",
	2: "JAVASCRIPT_SDK",
}
var APIAuthenticationMessage_Source_value = map[string]int32{
	"UNKNOWN":        0,
	"GOLANG_SDK":     1,
	"JAVASCRIPT_SDK": 2,
}

func (x APIAuthenticationMessage_Source) String() string {
	return proto.EnumName(APIAuthenticationMessage_Source_name, int32(x))
}
func (APIAuthenticationMessage_Source) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

// ClientMessage is a wrapper message used to describe the supplied client message
// and pass metadata about the client.
type ClientMessage struct {
	// Types that are valid to be assigned to Body:
	//	*ClientMessage_Identification
	//	*ClientMessage_Subscribe
	//	*ClientMessage_Unsubscribe
	//	*ClientMessage_WebAuthentication
	//	*ClientMessage_ApiAuthentication
	Body isClientMessage_Body `protobuf_oneof:"body"`
}

func (m *ClientMessage) Reset()                    { *m = ClientMessage{} }
func (m *ClientMessage) String() string            { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()               {}
func (*ClientMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isClientMessage_Body interface {
	isClientMessage_Body()
}

type ClientMessage_Identification struct {
	Identification *ClientIdentificationMessage `protobuf:"bytes,1,opt,name=identification,oneof"`
}
type ClientMessage_Subscribe struct {
	Subscribe *ClientSubscribeMessage `protobuf:"bytes,2,opt,name=subscribe,oneof"`
}
type ClientMessage_Unsubscribe struct {
	Unsubscribe *ClientUnsubscribeMessage `protobuf:"bytes,3,opt,name=unsubscribe,oneof"`
}
type ClientMessage_WebAuthentication struct {
	WebAuthentication *WebAuthenticationMessage `protobuf:"bytes,4,opt,name=webAuthentication,oneof"`
}
type ClientMessage_ApiAuthentication struct {
	ApiAuthentication *APIAuthenticationMessage `protobuf:"bytes,5,opt,name=apiAuthentication,oneof"`
}

func (*ClientMessage_Identification) isClientMessage_Body()    {}
func (*ClientMessage_Subscribe) isClientMessage_Body()         {}
func (*ClientMessage_Unsubscribe) isClientMessage_Body()       {}
func (*ClientMessage_WebAuthentication) isClientMessage_Body() {}
func (*ClientMessage_ApiAuthentication) isClientMessage_Body() {}

func (m *ClientMessage) GetBody() isClientMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *ClientMessage) GetIdentification() *ClientIdentificationMessage {
	if x, ok := m.GetBody().(*ClientMessage_Identification); ok {
		return x.Identification
	}
	return nil
}

func (m *ClientMessage) GetSubscribe() *ClientSubscribeMessage {
	if x, ok := m.GetBody().(*ClientMessage_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (m *ClientMessage) GetUnsubscribe() *ClientUnsubscribeMessage {
	if x, ok := m.GetBody().(*ClientMessage_Unsubscribe); ok {
		return x.Unsubscribe
	}
	return nil
}

func (m *ClientMessage) GetWebAuthentication() *WebAuthenticationMessage {
	if x, ok := m.GetBody().(*ClientMessage_WebAuthentication); ok {
		return x.WebAuthentication
	}
	return nil
}

func (m *ClientMessage) GetApiAuthentication() *APIAuthenticationMessage {
	if x, ok := m.GetBody().(*ClientMessage_ApiAuthentication); ok {
		return x.ApiAuthentication
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ClientMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ClientMessage_OneofMarshaler, _ClientMessage_OneofUnmarshaler, _ClientMessage_OneofSizer, []interface{}{
		(*ClientMessage_Identification)(nil),
		(*ClientMessage_Subscribe)(nil),
		(*ClientMessage_Unsubscribe)(nil),
		(*ClientMessage_WebAuthentication)(nil),
		(*ClientMessage_ApiAuthentication)(nil),
	}
}

func _ClientMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ClientMessage)
	// body
	switch x := m.Body.(type) {
	case *ClientMessage_Identification:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Identification); err != nil {
			return err
		}
	case *ClientMessage_Subscribe:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Subscribe); err != nil {
			return err
		}
	case *ClientMessage_Unsubscribe:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Unsubscribe); err != nil {
			return err
		}
	case *ClientMessage_WebAuthentication:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WebAuthentication); err != nil {
			return err
		}
	case *ClientMessage_ApiAuthentication:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ApiAuthentication); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ClientMessage.Body has unexpected type %T", x)
	}
	return nil
}

func _ClientMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ClientMessage)
	switch tag {
	case 1: // body.identification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClientIdentificationMessage)
		err := b.DecodeMessage(msg)
		m.Body = &ClientMessage_Identification{msg}
		return true, err
	case 2: // body.subscribe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClientSubscribeMessage)
		err := b.DecodeMessage(msg)
		m.Body = &ClientMessage_Subscribe{msg}
		return true, err
	case 3: // body.unsubscribe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClientUnsubscribeMessage)
		err := b.DecodeMessage(msg)
		m.Body = &ClientMessage_Unsubscribe{msg}
		return true, err
	case 4: // body.webAuthentication
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WebAuthenticationMessage)
		err := b.DecodeMessage(msg)
		m.Body = &ClientMessage_WebAuthentication{msg}
		return true, err
	case 5: // body.apiAuthentication
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(APIAuthenticationMessage)
		err := b.DecodeMessage(msg)
		m.Body = &ClientMessage_ApiAuthentication{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ClientMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ClientMessage)
	// body
	switch x := m.Body.(type) {
	case *ClientMessage_Identification:
		s := proto.Size(x.Identification)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_Subscribe:
		s := proto.Size(x.Subscribe)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_Unsubscribe:
		s := proto.Size(x.Unsubscribe)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_WebAuthentication:
		s := proto.Size(x.WebAuthentication)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_ApiAuthentication:
		s := proto.Size(x.ApiAuthentication)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// ClientIdentificationMessage is the first message sent is from the client to
// the server, identifying itself and the subscriptions it desires.
type ClientIdentificationMessage struct {
	Useragent     string   `protobuf:"bytes,1,opt,name=useragent" json:"useragent,omitempty"`
	Revision      string   `protobuf:"bytes,2,opt,name=revision" json:"revision,omitempty"`
	Integration   string   `protobuf:"bytes,3,opt,name=integration" json:"integration,omitempty"`
	Locale        string   `protobuf:"bytes,4,opt,name=locale" json:"locale,omitempty"`
	Subscriptions []string `protobuf:"bytes,5,rep,name=subscriptions" json:"subscriptions,omitempty"`
}

func (m *ClientIdentificationMessage) Reset()                    { *m = ClientIdentificationMessage{} }
func (m *ClientIdentificationMessage) String() string            { return proto.CompactTextString(m) }
func (*ClientIdentificationMessage) ProtoMessage()               {}
func (*ClientIdentificationMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClientIdentificationMessage) GetUseragent() string {
	if m != nil {
		return m.Useragent
	}
	return ""
}

func (m *ClientIdentificationMessage) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ClientIdentificationMessage) GetIntegration() string {
	if m != nil {
		return m.Integration
	}
	return ""
}

func (m *ClientIdentificationMessage) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *ClientIdentificationMessage) GetSubscriptions() []string {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type WebAuthenticationMessage struct {
	Identification *ClientIdentificationMessage `protobuf:"bytes,1,opt,name=identification" json:"identification,omitempty"`
	Token          string                       `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Nonce          string                       `protobuf:"bytes,3,opt,name=nonce" json:"nonce,omitempty"`
	AccessList     []string                     `protobuf:"bytes,4,rep,name=access_list,json=accessList" json:"access_list,omitempty"`
}

func (m *WebAuthenticationMessage) Reset()                    { *m = WebAuthenticationMessage{} }
func (m *WebAuthenticationMessage) String() string            { return proto.CompactTextString(m) }
func (*WebAuthenticationMessage) ProtoMessage()               {}
func (*WebAuthenticationMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *WebAuthenticationMessage) GetIdentification() *ClientIdentificationMessage {
	if m != nil {
		return m.Identification
	}
	return nil
}

func (m *WebAuthenticationMessage) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *WebAuthenticationMessage) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *WebAuthenticationMessage) GetAccessList() []string {
	if m != nil {
		return m.AccessList
	}
	return nil
}

type APIAuthenticationMessage struct {
	Token  string                          `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Nonce  string                          `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`
	ApiKey string                          `protobuf:"bytes,3,opt,name=api_key,json=apiKey" json:"api_key,omitempty"`
	Source APIAuthenticationMessage_Source `protobuf:"varint,4,opt,name=source,enum=ProtobufClient.APIAuthenticationMessage_Source" json:"source,omitempty"`
}

func (m *APIAuthenticationMessage) Reset()                    { *m = APIAuthenticationMessage{} }
func (m *APIAuthenticationMessage) String() string            { return proto.CompactTextString(m) }
func (*APIAuthenticationMessage) ProtoMessage()               {}
func (*APIAuthenticationMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *APIAuthenticationMessage) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *APIAuthenticationMessage) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *APIAuthenticationMessage) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *APIAuthenticationMessage) GetSource() APIAuthenticationMessage_Source {
	if m != nil {
		return m.Source
	}
	return APIAuthenticationMessage_UNKNOWN
}

// SubscribeMessage informs the Stream Hub to subscribe the current web socket to
// the supplied channel.
type ClientSubscribeMessage struct {
	SubscriptionKeys []string `protobuf:"bytes,1,rep,name=subscriptionKeys" json:"subscriptionKeys,omitempty"`
}

func (m *ClientSubscribeMessage) Reset()                    { *m = ClientSubscribeMessage{} }
func (m *ClientSubscribeMessage) String() string            { return proto.CompactTextString(m) }
func (*ClientSubscribeMessage) ProtoMessage()               {}
func (*ClientSubscribeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ClientSubscribeMessage) GetSubscriptionKeys() []string {
	if m != nil {
		return m.SubscriptionKeys
	}
	return nil
}

// UnsubscribeMessage informs the Stream Hub to unsubscribe the current web socket
// from the supplied channel.
type ClientUnsubscribeMessage struct {
	SubscriptionKeys []string `protobuf:"bytes,1,rep,name=subscriptionKeys" json:"subscriptionKeys,omitempty"`
}

func (m *ClientUnsubscribeMessage) Reset()                    { *m = ClientUnsubscribeMessage{} }
func (m *ClientUnsubscribeMessage) String() string            { return proto.CompactTextString(m) }
func (*ClientUnsubscribeMessage) ProtoMessage()               {}
func (*ClientUnsubscribeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ClientUnsubscribeMessage) GetSubscriptionKeys() []string {
	if m != nil {
		return m.SubscriptionKeys
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientMessage)(nil), "ProtobufClient.ClientMessage")
	proto.RegisterType((*ClientIdentificationMessage)(nil), "ProtobufClient.ClientIdentificationMessage")
	proto.RegisterType((*WebAuthenticationMessage)(nil), "ProtobufClient.WebAuthenticationMessage")
	proto.RegisterType((*APIAuthenticationMessage)(nil), "ProtobufClient.APIAuthenticationMessage")
	proto.RegisterType((*ClientSubscribeMessage)(nil), "ProtobufClient.ClientSubscribeMessage")
	proto.RegisterType((*ClientUnsubscribeMessage)(nil), "ProtobufClient.ClientUnsubscribeMessage")
	proto.RegisterEnum("ProtobufClient.APIAuthenticationMessage_Source", APIAuthenticationMessage_Source_name, APIAuthenticationMessage_Source_value)
}

func init() { proto.RegisterFile("client/client.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0xeb, 0x1c, 0xdc, 0xcf, 0x63, 0xd5, 0xca, 0x37, 0xa0, 0x62, 0x01, 0x12, 0x91, 0x85,
	0x50, 0x04, 0x52, 0x2a, 0x95, 0x2b, 0x2e, 0x4d, 0xab, 0x86, 0x90, 0x90, 0x46, 0x36, 0xa1, 0xdc,
	0x45, 0xb6, 0x3b, 0x0d, 0xab, 0x46, 0xb6, 0xe5, 0x5d, 0x83, 0xf2, 0x64, 0x70, 0xc1, 0xdb, 0xf0,
	0x22, 0xc8, 0xbb, 0x2e, 0xce, 0xc1, 0x41, 0x20, 0x71, 0xb5, 0x9e, 0xff, 0xce, 0xfc, 0x76, 0x0e,
	0xbb, 0x86, 0x7b, 0xd1, 0x92, 0x51, 0x2c, 0x4e, 0xd4, 0xd2, 0x4f, 0xb3, 0x44, 0x24, 0x68, 0x4d,
	0x8b, 0x25, 0xcc, 0x6f, 0xce, 0xa4, 0xea, 0x7c, 0x6b, 0xc2, 0x91, 0xfa, 0x7c, 0x47, 0x9c, 0x07,
	0x0b, 0xc2, 0x19, 0x58, 0xec, 0x9a, 0x62, 0xc1, 0x6e, 0x58, 0x14, 0x08, 0x96, 0xc4, 0xb6, 0xd6,
	0xd5, 0x7a, 0xe6, 0xe9, 0x8b, 0xfe, 0x66, 0x68, 0x5f, 0x2d, 0xc3, 0x0d, 0xdf, 0x12, 0xf2, 0xe6,
	0xc0, 0xdb, 0x82, 0xe0, 0x05, 0x18, 0x3c, 0x0f, 0x79, 0x94, 0xb1, 0x90, 0xec, 0x86, 0x24, 0x3e,
	0xab, 0x27, 0xfa, 0x77, 0x6e, 0x15, 0xac, 0x0a, 0xc5, 0x31, 0x98, 0x79, 0x5c, 0x91, 0x9a, 0x92,
	0xd4, 0xab, 0x27, 0xcd, 0x2a, 0xc7, 0x8a, 0xb5, 0x1e, 0x8e, 0x1f, 0xe1, 0xff, 0x2f, 0x14, 0xba,
	0xb9, 0xf8, 0x54, 0x24, 0x5b, 0xd6, 0xdb, 0xaa, 0x67, 0x5e, 0x6d, 0x3b, 0x56, 0xcc, 0x5d, 0x48,
	0x41, 0x0e, 0x52, 0xb6, 0x45, 0x6e, 0xd7, 0x93, 0xdd, 0xe9, 0x70, 0x2f, 0x79, 0x07, 0xf2, 0x5a,
	0x87, 0x56, 0x98, 0x5c, 0xaf, 0x9c, 0xaf, 0x1a, 0x3c, 0xfa, 0xcd, 0x0c, 0xf0, 0x31, 0x18, 0x39,
	0xa7, 0x2c, 0x58, 0x50, 0x2c, 0xe4, 0x0c, 0x0d, 0xaf, 0x12, 0xf0, 0x21, 0xfc, 0x97, 0xd1, 0x67,
	0xc6, 0x8b, 0xb4, 0x1a, 0x72, 0xf3, 0x97, 0x8d, 0x5d, 0x30, 0x59, 0x2c, 0x68, 0x91, 0xa9, 0xac,
	0x9b, 0x72, 0x7b, 0x5d, 0xc2, 0x63, 0xd0, 0x97, 0x49, 0x14, 0x2c, 0x49, 0x36, 0xcb, 0xf0, 0x4a,
	0x0b, 0x9f, 0xc2, 0x51, 0xd9, 0xdc, 0xb4, 0xf0, 0xe3, 0x76, 0xbb, 0xdb, 0xec, 0x19, 0xde, 0xa6,
	0xe8, 0x7c, 0xd7, 0xc0, 0xde, 0xd7, 0x4d, 0xf4, 0xff, 0xc1, 0xfd, 0xdb, 0xb9, 0x7d, 0xf7, 0xa1,
	0x2d, 0x92, 0x5b, 0xba, 0x2b, 0x55, 0x19, 0x85, 0x1a, 0x27, 0x71, 0x44, 0x65, 0x85, 0xca, 0xc0,
	0x27, 0x60, 0x06, 0x51, 0x44, 0x9c, 0xcf, 0x97, 0x8c, 0x0b, 0xbb, 0x25, 0x2b, 0x00, 0x25, 0x8d,
	0x19, 0x17, 0xce, 0x0f, 0x0d, 0xec, 0x7d, 0x23, 0xab, 0x4e, 0xd2, 0x6a, 0x4f, 0x6a, 0xac, 0x9f,
	0xf4, 0x00, 0x0e, 0x83, 0x94, 0xcd, 0x6f, 0x69, 0x55, 0x66, 0xa0, 0x07, 0x29, 0x1b, 0xd1, 0x0a,
	0x07, 0xa0, 0xf3, 0x24, 0xcf, 0x22, 0xd5, 0x5e, 0xeb, 0xf4, 0xe4, 0x4f, 0x6f, 0x4c, 0xdf, 0x97,
	0x61, 0x5e, 0x19, 0xee, 0xbc, 0x02, 0x5d, 0x29, 0x68, 0xc2, 0xe1, 0x6c, 0x32, 0x9a, 0x5c, 0x5e,
	0x4d, 0x3a, 0x07, 0x68, 0x01, 0x0c, 0x2e, 0xc7, 0xee, 0x64, 0x30, 0xf7, 0xcf, 0x47, 0x1d, 0x0d,
	0x11, 0xac, 0xb7, 0xee, 0x07, 0xd7, 0x3f, 0xf3, 0x86, 0xd3, 0xf7, 0x52, 0x6b, 0x38, 0xe7, 0x70,
	0x5c, 0xff, 0x1e, 0xf1, 0x39, 0x74, 0xd6, 0xe7, 0x39, 0xa2, 0x15, 0xb7, 0x35, 0xd9, 0xa5, 0x1d,
	0xdd, 0xb9, 0x00, 0x7b, 0xdf, 0x5b, 0xfc, 0x1b, 0x4e, 0xa8, 0xcb, 0xdf, 0xd7, 0xcb, 0x9f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x91, 0x32, 0xe0, 0x0c, 0xd5, 0x04, 0x00, 0x00,
}
